language: php
php:
  - 5.5
  
before_script:
 - composer install

script:
 - phpunit
 
notifications:
  hipchat:
    rooms:
      - 70ca4e94854d0e741b7e01790e2a6a@Patinthehat
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true